### ISSUE TITLE
The /build directory should be removed when one pulls a new version of TedStudley/mc-mini/master

### ISSUE THREAD

**Issue by egpuckett** [TedStudley/mc-mini#17]
I believe ASPECT has this feature.  It ensures one does not accidentally run an old version of mc-mini after updating the master.

**Comment by TedStudley** [comment]
I'm still not sure if this is entirely possible without setting up a post-pull hook in a way that isn't necessarily  very elegant or portable. To add to that, removing the entire build directory would also clobber all of the files which haven't changed, meaning that even if the pull was a small change, we would need to recompile everything, including re-downloading the GTest libraries, etc...

I think it would be better just to make it a habit to run the test suite whenever you pull a new version. This will automatically recompile all changed source files, and has the added benefit that we see easily whether anything was broken by the pull. I think automating anything more than that would fall under the umbrella of "things I don't expect a project to do automatically", and so probably wouldn't be great to include.

**Comment by TedStudley** [comment]
Closing as not possible/not a project priority
