### ISSUE TITLE
Need a README to explain how to build once one clones the master branch.

### ISSUE THREAD

**Issue by egpuckett** [TedStudley/mc-mini#18]
One needs to have Eigen_v-3.2.x in /usr/local/include and in ~/.bashrc set

  export EIGEN3_INCLUDE_DIR="/usr/local/include"

(master) $ mkdir build
 
(master) $ cd build

(master) $ cmake ..

 (master) $ make

**Comment by TedStudley** [comment]
It shouldn't be necessary to have the EIGEN3_INCLUDE_DIR environment variable set... Have you tried building without that?

The rest is all correct, though.

**Comment by egpuckett** [comment]
I can try.  Tomorrow ... I'm totally burnt today.  Harsha thought it was necessary.

- Gerry

**Comment by TedStudley** [comment]
Did you ever get a chance to look into this? I'd like to see if there's something I need to change with the build script... if it's not finding Eigen by default, there's something wrong.

**Comment by TedStudley** [comment]
Added a section in the README to explain how the project is built. There's more that could be added there, but it should work fine for now.

I never heard whether the provided instructions work for everybody or not, so I'm closing this issue. If anybody has issues building with the provided commands, it can be addressed in a separate issue.
